export const READER_ACTIONS = {
    GET_CHAPTER_PAGES: "GET_CHAPTER_PAGES", 
    GET_CHAPTER_PAGES_SUCCESS: "GET_CHAPTER_PAGES_SUCCESS", 
    GET_CHAPTER_PAGES_ERROR: "GET_CHAPTER_PAGES_ERROR",
    SET_READER_MODE: "SET_READER_MODE",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_STATUS_FINISHED: "SET_STATUS_FINISHED",
    SET_LOADING_RANGE: "SET_LOADING_RANGE",
    LOAD_CONFIG: "LOAD_CONFIG",
    CHAPTER_NAVIGATION: "CHAPTER_NAVIGATION",
    EFFECT_CLEAN_UP: "EFFECT_CLEAN_UP",
    SHOW_MODAL: "SHOW_MODAL",
}